EZEE-3485: ezcommerce 3.3 compatibility & schema definition
ezsystems/ezplatform-rest-reference pull request #12
Opened 2021-03-08 10:39 UTC by Steveb-p

2021-03-18 15:00 UTC, DominikaK requested changes
Reminder: add generated index.md before merging

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +        displayName: Reads list of baskets. Returns wishlist/stored baskets.
```suggestion
        displayName: Read list of baskets
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +            <br />Warning: Only "storedBasket" and "wishList" types are handled. Others will return validation error.
```suggestion
            Returns baskets for the current user. Only "storedBasket" and "wishList" types are handled. Others will return validation error.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                displayName: Update party (buyer, delivery, invoice) information in the basket.
```suggestion
                displayName: Update party information in the basket
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                displayName: Update the name or the note of the stored basket.
```suggestion
                displayName: Update the name or the note of the stored basket
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                    displayName: Add lines to basket fields for item data, provided via POST data and parsed
```suggestion
                    displayName: Add lines to basket fields
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +            displayName: Gets list of payment methods.
```suggestion
            displayName: Get list of payment methods
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +            displayName: Gets list of shipping methods.
```suggestion
            displayName: Get list of shipping methods
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +        displayName: Gets list of shipping addresses from customer.
```suggestion
        displayName: Get list of shipping addresses
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                displayName: Update and checks voucher in current basket
```suggestion
                displayName: Update and check voucher in current basket
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                description: Update and checks voucher in current basket
```suggestion
                description: Updates and checks voucher in current basket.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                    This adds basket lines into current basket in user session, if any, using basket stored in permanent
```suggestion
                    Adds basket lines into current basket in user session, if any, using basket stored in permanent
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                description: Update shipping information in current basket
```suggestion
                description: Updates shipping information in the current basket.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                description: Update party (buyer, delivery, invoice) information in the basket.
```suggestion
                description: Updates party (buyer, delivery, invoice) information in the basket.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                description: Update payment information in current basket
```suggestion
                description: Updates payment information in the current basket.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                description: Add products to current basket
```suggestion
                description: Adds products to the current basket.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +            description: Get Basket by ID
```suggestion
            description: Gets basket by ID.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +                    Update the name or the note of the stored basket.
```suggestion
                    Updates the name or the note of the stored basket.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +            description: Create a new persisted basket
```suggestion
            description: Creates a new persisted basket.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +        description: Get customer prices for the requested products
```suggestion
        description: Gets customer prices for the requested products.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +        displayName: Get customer prices for the requested products
```suggestion
        displayName: Get customer prices for products
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +        description: Add to basket the line from a CSV or Excel file
```suggestion
        description: Adds to basket a line from a CSV or Excel file.
```

2021-03-18 15:00 UTC, DominikaK commented on input/ez-commerce.raml
> +        displayName: Add to basket the line from a CSV or Excel file
```suggestion
        displayName: Add to basket from CSV or Excel
```

2021-03-19 07:35 UTC, Nattfarinn approved these changes

2021-03-22 08:38 UTC, DominikaK approved these changes

2021-05-05 06:42 UTC, merged